blank_issues_enabled: false
contact_links:
  - name: Twentig support
    url: https://wordpress.org/support/plugin/twentig/
    about: For support related questions, please create a new topic in our WordPress.org support forum.
